- hosts: local
  vars_files:
     - namenode_varfile.yml
  tasks:
  - name: Copying jdk file to the target node
    copy:
     src: "{{ jdk_path }}"
     dest: "/root/"

  - name: Copying hadoop rpm file to target node
    copy:
     src: "{{ hadoop_path }}"
     dest: "/root/"

  - name: Installing Jdk software
    shell: rpm -ivh jdk-8u171-linux-x64.rpm

  - name: Installing Hadoop software
    shell: rpm -ivh hadoop-1.2.1-1.x86_64.rpm  --force

  - name: Configuring the hdfs-site.xml file
    copy:
      src: "{{ hdfs_site_file }}"
      dest: "/etc/hadoop/"
   
  - name: Configuring the core-site.xml file
    copy:
      src: "{{ core_site_file }}"
      dest: "/etc/hadoop/"


  - name: Deleting the name-node directory if exists
    shell: rm -rf /nn1
    ignore_errors: yes

  - name: Creating a name-node directory
    file:
      state: directory
      path: /nn1

  - name: "Formatting the directory"
    command: hadoop namenode -format -force

  - name: "Starting the namenode"
    command: hadoop-daemon.sh start namenode
 
  - name: "Java Process"
    shell: jps
    register: jps
  - name: "Java Process"
    debug:
     var: jps.stdout



